# Generated by Django 3.2.11 on 2023-08-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_count_app', '0002_companydatamodel_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydatamodel',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
